In [5]:
import torch.nn as nn
import torch

In [6]:
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

In [7]:
input

tensor([[[ 1.6272e-01,  5.7167e-01, -6.9081e-01, -4.2186e-01, -4.6698e-01,
           6.8661e-01,  2.8021e-01,  1.0726e+00,  2.7598e-02, -1.7076e+00],
         [-9.5042e-01,  5.4722e-01,  5.4843e-01, -5.4240e-01, -1.3527e+00,
           2.3385e+00,  2.8807e-01, -4.0619e-03,  1.2189e+00, -1.3509e+00],
         [ 1.3677e+00,  1.5133e+00, -1.6565e+00,  1.2839e+00,  8.4954e-01,
          -2.2185e-01,  4.5945e-01, -4.5999e-01,  8.5011e-01, -2.5282e+00]],

        [[ 8.6823e-01, -1.5257e+00, -7.0837e-01, -1.5566e-01,  5.5873e-01,
          -3.8835e-01,  2.3072e-01, -6.7144e-01,  1.3150e+00,  1.9479e-02],
         [-1.0178e-01, -2.9440e-01,  9.1190e-01,  1.2272e+00, -5.8841e-01,
           5.4130e-01,  2.7325e+00, -5.2502e-02, -3.4626e-01, -1.2990e+00],
         [-8.6128e-01, -6.1290e-01,  9.9329e-01,  2.0218e-01, -4.3745e-01,
           1.8494e-01,  3.4407e-01,  4.1258e-02,  1.4026e-01,  5.1868e-01]],

        [[ 2.5706e-01, -1.6582e-01,  1.9470e-01, -2.7917e-01, -1.3666e+00,
           9.65

In [8]:
h0

tensor([[[-1.2944, -0.3796,  0.0829,  0.2020,  1.2615,  0.5852, -0.0169,
           0.5696,  0.6517, -0.2074, -2.2309,  1.1131,  0.6743, -0.5555,
          -1.0043, -1.7898, -0.6235, -0.5822,  1.8194, -1.3362],
         [-0.8191,  0.0657,  0.4988,  2.1348, -0.9114, -0.4064, -0.7733,
           2.0882, -0.7322, -0.5548, -0.3024,  1.7990,  0.5843, -0.1690,
           0.4700, -0.5828,  1.1800,  0.2469, -0.7312, -0.8317],
         [-0.1982, -0.1699,  1.2393,  0.4778, -2.2298,  2.5774,  0.2358,
          -1.1649,  0.0880,  0.8328, -0.9280,  1.2767, -1.0727,  1.4551,
          -1.0257,  0.2509, -0.1393,  1.2110, -0.1167, -0.9111]],

        [[-1.0994, -1.4062,  0.1955,  1.6791,  0.5353,  0.3495, -0.4007,
           1.1235, -0.0584, -0.1315, -0.4916, -1.4690, -0.1820,  0.8013,
           0.1771, -0.3998,  0.5868,  0.0572, -0.1637,  0.3405],
         [-1.4515, -1.0665, -0.7936, -1.2517, -0.5915,  1.5696, -1.7244,
           0.2767, -2.0120, -0.8050,  0.0725, -2.3324,  2.0761,  0.5936,
        

In [10]:
c0

tensor([[[-0.1527, -0.9365,  0.4527,  1.3456,  0.2133,  0.0285,  0.9593,
          -0.8274, -1.7038, -0.2780,  1.1471,  0.1615,  0.0710, -0.1166,
           0.0888,  2.3757, -0.1596,  1.8344, -0.1416,  0.3220],
         [ 1.7794, -1.3331,  0.7798,  0.1979, -0.6854,  0.0563, -1.4900,
          -0.6830,  0.9215, -0.8246,  0.6054,  0.0872,  0.1624, -1.5549,
           1.4662, -1.3820,  0.4945,  0.6220,  0.9127,  0.4219],
         [-1.2138,  0.5588,  2.3073,  0.0294, -0.3124,  0.6142, -2.1299,
          -0.4229, -1.4252,  1.0769,  0.9785, -1.1440,  0.0235,  0.9041,
          -0.7431, -1.2054, -1.0571, -0.2475, -0.5266, -0.6197]],

        [[-0.8459, -0.7868,  0.0924, -0.0424, -0.3105, -0.6768,  2.2975,
          -0.2088, -1.1493,  0.6771,  0.7018,  1.9211,  0.7350,  0.1796,
          -2.4463, -0.2538,  0.5978,  1.3299,  1.1682,  1.0783],
         [ 0.1374, -0.7054,  0.6805, -1.5742,  0.2147, -1.4556,  0.3939,
          -0.8416,  0.3854, -0.5095,  0.0994,  0.8630, -1.5734, -1.4079,
        

In [12]:
output

tensor([[[-3.6443e-01, -1.7356e-01, -5.1764e-02,  4.7064e-02, -4.2021e-02,
          -7.9108e-02,  1.1439e-01, -6.5773e-02, -3.5329e-01,  7.9155e-02,
           7.6589e-02,  5.1654e-01,  3.2001e-01, -9.6165e-02, -4.8683e-01,
          -1.0234e-01,  1.9145e-01,  4.4849e-01,  1.4726e-01,  2.1962e-01],
         [-2.6032e-01, -1.0206e-01,  7.3465e-03, -4.9742e-01, -2.3031e-01,
          -3.3664e-01, -5.9625e-02, -2.5226e-01, -1.5815e-01,  4.3284e-02,
           1.4462e-02,  2.9159e-01, -5.4461e-01, -3.9175e-01, -5.3038e-01,
          -5.8176e-03, -2.3657e-01,  7.5703e-03,  1.4171e-01, -4.9984e-01],
         [-1.8131e-01, -2.7918e-01,  2.3577e-01, -3.4447e-02, -7.0469e-02,
          -8.2915e-02,  5.6599e-02,  8.5059e-03,  3.4700e-01,  9.3941e-03,
          -1.2027e-02, -1.6396e-01, -2.1816e-02,  2.3217e-01, -1.3563e-01,
          -1.2708e-01,  2.1750e-01, -3.7975e-04, -1.1964e-01, -1.7754e-01]],

        [[-2.9322e-01, -1.0777e-01, -7.7730e-02,  2.5595e-02, -4.2442e-02,
          -4.3761e-0