# 一维数据

In [1]:
#列表
[1,2,'a',4]

[1, 2, 'a', 4]

In [2]:
import numpy as np
np.array([1,'a',3,4])

array(['1', 'a', '3', '4'], dtype='<U11')

In [3]:
set([1,'a',3,4])

{1, 3, 4, 'a'}

In [4]:
tuple([1,'a',3,4])

(1, 'a', 3, 4)

# 二维数据

In [6]:
[[1,2,3],['a','b','c']]

[[1, 2, 3], ['a', 'b', 'c']]

In [8]:
np.array([[1,2,3],['a','b','c']])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [10]:
import pandas as pd
pd.DataFrame([[1,2,3],['a','b','c']],columns=['A','B','C'],index=[0,1])

A  B  C
0  1  2  3
1  a  b  c

In [12]:
pd.DataFrame(np.array([[1,2,3],['a','b','c']]),columns=['A','B','C'],index=[1,2])

A  B  C
1  1  2  3
2  a  b  c

# 三维数据

In [15]:
a = [[[1,2],[3,4]],[[5,6],[7,8]]]
a[0]

[[1, 2], [3, 4]]

In [17]:
pd.DataFrame(a,columns=['a','b'],index=[0,1])

a       b
0  [1, 2]  [3, 4]
1  [5, 6]  [7, 8]

# Numpy的ndarray具有广播功能

In [18]:
import numpy as np
np.__version__

'1.19.5'

In [20]:
np.array?

In [22]:
a=[1,2,3,4]
c=[]
for i in a:
    c.append(i**2)
print(c)

[1, 4, 9, 16]


In [23]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16], dtype=int32)

# Numpy数组的性能比Python原生数据类型高

In [24]:
def add(n):
    a=[]
    b=[]
    c=[]
    for i in range(n):
        a.append(i**2)
        b.append(i+3)
        c.append(a[i]+b[i])
    return c

def np_add(n):
    a=np.arange(n)**2
    b=np.arange(n)+3
    c=a+b

In [25]:
N=1000000

In [28]:
%timeit add(N)

561 ms ± 6.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%timeit np_add(N)

8.19 ms ± 114 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object 

# ndarray的基本属性

In [31]:
a=np.array([[1,2,3],[4,5,6]])
type(a)

numpy.ndarray

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a.shape

(2, 3)

In [34]:
a.size

6

In [35]:
a.ndim

2

In [37]:
a.dtype

dtype('int32')

In [38]:
a.itemsize

4

In [39]:
a[0][0]

1

# ndarray元素类型

In [41]:
b=np.array([[1,2,3,4],['a','b','c','d']])

In [42]:
b

array([['1', '2', '3', '4'],
       ['a', 'b', 'c', 'd']], dtype='<U11')

In [43]:
b.size

8

In [44]:
c = np.array([[1,2,3,4],['a','b','c','d'],[5,6,7]])

E:\Temp\ipykernel_2732\248453217.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  c = np.array([[1,2,3,4],['a','b','c','d'],[5,6,7]])


In [45]:
c

array([list([1, 2, 3, 4]), list(['a', 'b', 'c', 'd']), list([5, 6, 7])],
      dtype=object)

In [46]:
c.size

3

# 创建ndarray的方式

In [47]:
np.array([[1,2,3],[4,5,6]],dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [48]:
array_01=np.array([[1,2,3],[4,5,6]])
array_01.dtype

dtype('int32')

In [51]:
np.array([(1,2),(2,3)])

array([[1, 2],
       [2, 3]])

In [52]:
np.array([[1,2,3,4],[4,5,6,7]])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [53]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [54]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [56]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [57]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
array_03=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,0]])
array_03

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [62]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
print(a.shape,b.shape)

(2, 2) (1, 2)


In [66]:
b.T

array([[5],
       [6]])

In [67]:
b.T.shape

(2, 1)

In [70]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# ndaray对象的变换

In [73]:
a=np.linspace(1,24,24,dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [74]:
b=a.reshape(4,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [75]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [77]:
a.resize(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [78]:
a.swapaxes(1,0)

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [79]:
c=a.flatten()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [80]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [81]:
b=np.linspace(1,9,9)
b.resize(3,3)
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [82]:
b.dtype

dtype('float64')

In [84]:
d=b.astype(np.int16)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [85]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [86]:
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

# ndarray对象的操作