In [15]:
import numpy as np

In [16]:
list(range(10))
print(np.arange(0,20,2))
print(np.random.random((3,3)))
print(np.random.normal(0, 1, (3,3)))
print(np.random.randn(3,3))
print(np.eye(3))
print(np.empty(3))
print(np.random.seed(10))
x1 = np.random.randint(10, size=(3,4))
x1[0,0] 
x1[2:,1:3]
grid = np.arange(1,10)
grid.reshape(3,3)
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])
grid1 = np.array([[1, 2, 3],
            [4, 5, 6]])
print(np.concatenate([grid1, grid1], axis=1))
print('np.vstack垂直栈同axis=0\n', np.vstack([x, y, z, grid1]))
print('np.hstack水平栈同axis=1\n', np.hstack([grid1, grid1]))
x = [0, 1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5])
grid = np.arange(16).reshape(4, 4) 
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [1])
print(left)
print(right)
# print(x1, x2, x3)
x = np.arange(4)
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.floor_divide(x, 5))
print(np.mod(x, 2))
print(np.power(x, 3))
print(np.negative(x))
print(np.abs(x))
theta = np.linspace(0, np.pi, 3)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))
print(np.arcsin(theta))
print(np.arccos(theta))
print(np.arctan(theta))
xn = np.arange(1, 4)
print(np.exp(xn))
print(np.exp2(xn))
print(np.power(3, xn))
print(np.log(xn))
print(np.log2(xn))
print(np.log10(xn)) 
x = np.arange(5)
y = np.empty(5)
z = np.zeros(10)    
print(np.multiply(x, 10, out = y))
print(np.power(2, x, out = z[::2]))
print(z)
print('x中所有元素求和：', np.add.reduce(x))
print('x中所有元素求积：', np.multiply.reduce(x))
print('x中所有元素依次求和并展示：', np.add.accumulate(x))
print('x中所有元素依次求积并展示：', np.multiply.accumulate(x))
print(np.multiply.outer(x, x))

[ 0  2  4  6  8 10 12 14 16 18]
[[0.68535982 0.95339335 0.00394827]
 [0.51219226 0.81262096 0.61252607]
 [0.72175532 0.29187607 0.91777412]]
[[ 0.35365794  1.78370094 -0.35030121]
 [-0.9896496  -0.63425417  1.89876222]
 [ 1.99652279 -1.11867153  2.18032831]]
[[ 0.19046688  1.2616859   0.41765968]
 [ 0.89395769  0.04735517 -0.60842552]
 [-0.26854813 -0.66630197 -0.34401183]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]
None
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
np.vstack垂直栈同axis=0
 [[ 1  2  3]
 [ 3  2  1]
 [99 99 99]
 [ 1  2  3]
 [ 4  5  6]]
np.hstack水平栈同axis=1
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 0 0]
[0 1 0 1]
[ 0  1  8 27]
[ 0 -1 -2 -3]
[0 1 2 3]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+

C:\Windows\Temp\ipykernel_12548\1693188234.py:47: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(theta))
C:\Windows\Temp\ipykernel_12548\1693188234.py:48: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(theta))


## 关卡 1:数组的创建与计算

In [17]:
a = np.arange(1,19)
b = np.arange(19, 49)
A = a.reshape(3,6)
B = b.reshape(5,6)
C = np.vstack([A,B])
N, D = np.split(C, [1])
E = D[1]
a1 = np.multiply.accumulate(E)[-1]
a1

13366080

## 关卡 2:数组聚合与广播

## 关卡 3:数组的比较与索引

## 关卡 4:数组排序与结构化数组

## 关卡 5:综合实战

In [ ]:
def save_csv(a1):
    import pandas as pd
    df = pd.DataFrame({"id": ["q1"], "answer": [a1]})
    df.to_csv("answer_1.csv", index=None)
save_csv(a1)